name: Rubocop

on: [push, pull_request]

jobs:
  build:
    name: Rubocop
    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: [
          2.7
        ]

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e
      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace
        with:
          path: /home/runner/bundle
          key: bundle-use-ruby-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-gems-

      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Bundle install
        run: |
          gem install bundler -v 2.1.4
          bundle config path /home/runner/bundle
          bundle install

      - name: Ruby linter
        run: bundle exec rubocop
